name: torch
channels:
  - default
  - pytorch
  - powerai
  - comet_ml
  - conda-forge
dependencies:
  - cudatoolkit=10.1
  - cudnn=7
  - nccl
  - pytorch
  - torchvision
  - tensorflow-gpu
  - tensorflow-hub
  - tensorflow-gan
  - comet_ml
  - matplotlib
  - opencv